site_name: Mcpy Docs

theme:
  name: "material"
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences

plugins:
  - mkdocstrings

nav:
- Home: index.md
- Get Started: get-started.md
- working-with-commands.md
- how-to-include-dependencies.md
- Mcpy API Reference: reference.md
- Command API Reference: cmd_reference.md
