site_name: Mcpy Docs

theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 


        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences

plugins:
  - mkdocstrings

nav:
- Home: index.md
- Get Started: get-started.md
- working-with-commands.md
- how-to-include-dependencies.md
- Mcpy API Reference: reference.md
- Command API Reference: cmd_reference.md
